version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.0
    - 7.23.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: extract-react-types
    versions:
    - 0.28.0
    - 0.29.0
    - 0.29.1
    - 0.29.3
    - 0.30.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
